name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**'
      - '!README.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          yarn
          yarn tsc
          yarn format
          yarn lint